import { CheckCircle2, ArrowLeft, ArrowRight } from "lucide-react";
import Navbar from "../../../components/navbar/Navbar";
import Footer from "../../../components/footer/Footer";
import { useNavigate } from "react-router-dom";
import ProgressSteps from "../../../components/Common/ProgressSteps";

const PreviewStep = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      <Navbar />

      {/* Main Content */}
      <div className="flex-1 flex items-center justify-center px-5 md:px-10 py-8 sm:py-12">
        <div className="w-full container mx-auto">
          {/* Progress Bar - Responsive */}

          <ProgressSteps activeStep={3} />

          {/* Main Card */}
          <div className="bg-white rounded-3xl shadow-lg border border-gray-50 p-4 sm:p-10 md:p-12">
            {/* Title */}
            <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold text-center text-gray-900 mb-3">
              Preview Your Insole
            </h1>
            <p className="text-center text-gray-600 mb-8 sm:mb-12 text-sm sm:text-base">
              Review your customized insole design before downloading
            </p>

            {/* 3D Preview Area */}
            <div className="bg-gray-50 rounded-3xl p-4 sm:p-10 mb-8">
              <h3 className="text-lg sm:text-xl font-semibold text-gray-800 mb-6 sm:mb-8 text-center sm:text-left">
                3D Preview
              </h3>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 sm:gap-10">
                {/* Left Foot */}
                <div className="bg-white rounded-3xl p-4 sm:p-6 shadow-md text-center">
                  <div className=" py-2 bg-[#F0FDF4] border border-[#016630] text-[#016630] md:text-base text-sm font-bold rounded-full max-w-max px-2 mb-5">
                    Uploaded Scan
                  </div>
                  <div className="mb-4 sm:mb-6 aspect-square max-w-sm mx-auto">
                    <model-viewer
                      src="https://ar-menu-bucket-jvai-files.s3.ap-south-1.amazonaws.com/static_files/right.glb"
                      alt="Left foot insole 3D model"
                      shadow-intensity="1"
                      camera-controls
                      touch-action="pan-y"
                      auto-rotate
                      style={{ width: "100%", height: "100%" }}
                      className="rounded-2xl"
                    />
                  </div>
                  <p className="text-base sm:text-lg font-medium text-gray-800">
                    Left foot insole
                  </p>
                </div>

                {/* Right Foot */}
                <div className="bg-white rounded-3xl p-4 sm:p-6 shadow-md text-center">
                  <div className=" py-2 bg-[#FDFFCE] border border-[##FDFFCE] text-[#A27E1A] md:text-base text-sm font-bold rounded-full max-w-max px-2 mb-5">
                    AI Generated / Mirror
                  </div>
                  <div className="mb-4 sm:mb-6 aspect-square max-w-sm mx-auto">
                    <model-viewer
                      src="https://ar-menu-bucket-jvai-files.s3.ap-south-1.amazonaws.com/static_files/right.glb"
                      alt="Left foot insole 3D model"
                      shadow-intensity="1"
                      camera-controls
                      touch-action="pan-y"
                      auto-rotate
                      style={{ width: "100%", height: "100%" }}
                      className="rounded-2xl"
                    />
                  </div>
                  <p className="text-base sm:text-lg font-medium text-gray-800">
                    Right foot insole
                  </p>
                </div>
              </div>
            </div>

            <div className="mb-6 border border-gray-50 shadow px-4 py-3 rounded-xl md:text-lg">
              <span className="font-bold">Note: </span> Insoles without uploaded
              scans are generated by AI or mirroring the opposite foot.
            </div>

            {/* Uploaded Files */}
            <div className="bg-gray-50 rounded-3xl p-6 sm:p-8 mb-8">
              <h3 className="font-semibold text-lg mb-4">Uploaded Files</h3>
              <div className="space-y-3">
                {["foot_scan.jpg", "foot_scan.obj"].map((file) => (
                  <div key={file} className="flex items-center gap-3">
                    <CheckCircle2 className="w-5 h-5 sm:w-6 sm:h-6 text-green-500 flex-shrink-0" />
                    <span className="text-gray-700 text-sm sm:text-base">
                      {file}
                    </span>
                  </div>
                ))}
              </div>
            </div>

            {/* Success Message */}
            <div className="bg-green-50 border border-green-200 text-green-700 px-6 sm:px-8 py-4 rounded-3xl text-center font-medium mb-10 text-sm sm:text-base">
              Your design looks great! Click continue to download the files for
              3D printing.
            </div>

            {/* Navigation Buttons */}
            <div className="flex flex-col sm:flex-row gap-4 justify-between">
              <button
                onClick={() => navigate(-1)}
                className="order-2 sm:order-1 px-10 py-2.5 border border-gray-300 text-gray-700 text-sm sm:text-base font-semibold rounded-3xl cursor-pointer hover:bg-gray-50 transition flex items-center justify-center gap-2">
                <ArrowLeft size={20} />
                Previous
              </button>

              <button
                onClick={() => navigate("/custom/download")}
                className="order-1 sm:order-2 bg-[#009FF2] hover:bg-[#0088d1] text-white font-bold text-sm sm:text-base px-12 py-3 rounded-3xl cursor-pointer shadow-lg hover:shadow-xl transition flex items-center justify-center gap-3">
                Next
                <ArrowRight size={24} />
              </button>
            </div>
          </div>
        </div>
      </div>

      <Footer />
    </div>
  );
};

export default PreviewStep;
